language: python

python:
    - '3.6'

install:
  - pip install pytest
  - pip install cython
  - pip install --editable .
  - pip list

script:
    - python setup.py test

after_success: 
  - coveralls

notifications:
  email: false